services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: tbps
      POSTGRES_PASSWORD: tbps
      POSTGRES_DB: tbps_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
